### ISSUE TITLE
Unable to operate nodes

### ISSUE THREAD

**Issue by Trobinou** [taabata/LCM_Inpaint_Outpaint_Comfy#12]
As I can't get your nodes to work, I've been looking at the current issues to find a solution. I can see that I'm not the only one, and the problems are all linked to the fact that it seems that installing your nodes isn't easy for us simple users.

Could you please tell us the following: 
- Exactly what files your nodes pack needs to work, 
- Where these files should be located, 
- The link to download each of these files.

We hope that your reply will help us to use your pack, which looks great.

Thank you

**Comment by taabata** [comment]
Hey, let me know what error you're facing exactly.

**Comment by Trobinou** [comment]
Thanks for your answer.
I've updated the diffusers,
```
  Downloading diffusers-0.24.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: Pillow in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from diffusers) (10.0.1)
Requirement already satisfied: filelock in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from diffusers) (3.12.2)
Collecting huggingface-hub>=0.19.4 (from diffusers)
  Downloading huggingface_hub-0.19.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: importlib-metadata in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from diffusers) (6.8.0)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from diffusers) (1.26.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from diffusers) (2023.8.8)
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from diffusers) (2.31.0)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from diffusers) (0.3.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.19.4->diffusers) (2023.9.2)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.19.4->diffusers) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.19.4->diffusers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.19.4->diffusers) (4.7.1)
Requirement already satisfied: packaging>=20.9 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.19.4->diffusers) (23.1)
Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata->diffusers) (3.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests->diffusers) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests->diffusers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests->diffusers) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests->diffusers) (2023.7.22)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.19.4->diffusers) (0.4.6)
Downloading diffusers-0.24.0-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 1.8/1.8 MB 542.5 kB/s eta 0:00:00
Downloading huggingface_hub-0.19.4-py3-none-any.whl (311 kB)
   ---------------------------------------- 311.7/311.7 kB 551.1 kB/s eta 0:00:00
Installing collected packages: huggingface-hub, diffusers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.17.3
    Uninstalling huggingface-hub-0.17.3:
      Successfully uninstalled huggingface-hub-0.17.3
Successfully installed diffusers-0.24.0 huggingface-hub-0.19.4
```
but unfortunately the nodes are still inaccessible

```
Traceback (most recent call last):
  File "D:\ComfyUI_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM_Nodes.py", line 15, in <module>
    from .LCM.stable_diffusion_reference_img2img import StableDiffusionImg2ImgPipeline_reference
  File "D:\ComfyUI_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM\stable_diffusion_reference_img2img.py", line 23, in <module>
    from diffusers.loaders import FromSingleFileMixin, LoraLoaderMixin, TextualInversionLoaderMixin, IPAdapterMixin
ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (D:\ComfyUI_portable\python_embeded\Lib\site-packages\diffusers\loaders.py)

Cannot import D:\ComfyUI_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy module for custom nodes: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (D:\ComfyUI_portable\python_embeded\Lib\site-packages\diffusers\loaders.py)
```
