### ISSUE TITLE
I installed the requirements and all but it always fail to load

### ISSUE THREAD

**Issue by if-ai** [taabata/LCM_Inpaint_Outpaint_Comfy#13]
OpenPose Editor: Loaded
Traceback (most recent call last):
  File "/home/impactframes/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/impactframes/ComfyUI/custom_nodes/LCM_Inpaint-Outpaint_Comfy/__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "/home/impactframes/ComfyUI/custom_nodes/LCM_Inpaint-Outpaint_Comfy/LCM_Nodes.py", line 15, in <module>
    from .LCM.LCM_lora_inpaint import LCM_inpaint_final
  File "/home/impactframes/ComfyUI/custom_nodes/LCM_Inpaint-Outpaint_Comfy/LCM/LCM_lora_inpaint.py", line 27, in <module>
    from diffusers.loaders import FromSingleFileMixin, IPAdapterMixin, LoraLoaderMixin, TextualInversionLoaderMixin
ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (/home/impactframes/micromamba/envs/comfy/lib/python3.10/site-packages/diffusers/loaders.py)

Cannot import /home/impactframes/ComfyUI/custom_nodes/LCM_Inpaint-Outpaint_Comfy module for custom nodes: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (/home/impactframes/micromamba/envs/comfy/lib/python3.10/site-packages/diffusers/loaders.py)
Using xformers cross attention
### ComfyUI Revision: 1773 [6efe561c] | Released on '2023-12-03'
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: /home/impactframes/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
FizzleDorf Custom Nodes: Loaded

**Comment by if-ai** [comment]
> i think you need to update the diffusers library

Yes, that was the issue, I was on 0.23 updated and on 0.25 dev0 it works. Now my only wish is for this to be able to work with the lora's LCM workflow instead of just the dreamshaperlcm, I will try it today. Thank you.
