### ISSUE TITLE
NameError: name 'ImageSwitch' is not defined

### ISSUE THREAD

**Issue by awilliamson** [taabata/LCM_Inpaint_Outpaint_Comfy#21]
Traceback:
```
Traceback (most recent call last):
  File "/home/ashley/GitHubProjects/ComfyUI/nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ashley/GitHubProjects/ComfyUI/custom_nodes/LCM_Inpaint_Outpaint_Comfy/__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "/home/ashley/GitHubProjects/ComfyUI/custom_nodes/LCM_Inpaint_Outpaint_Comfy/LCM_Nodes.py", line 2956, in <module>
    "ImageSwitch":ImageSwitch,
                  ^^^^^^^^^^^
NameError: name 'ImageSwitch' is not defined
```

ImageStitch is not imported whatsoever within LCM_Nodes.py from my cursory checking. This was introduced in ce0f73115e6e3afd7281b8be64741789e31c3f95 by @taabata 

This breaks the mix_workflow.json as ImageStitch is required.

**Comment by taabata** [comment]
code updated. Let me know if you still face errors.

**Comment by pengtb** [comment]
updating to the latest version fixes. thanks.
