### ISSUE TITLE
Node fails to load, it appears that the RIVAL source was supposed to be included with this node but isn't in the repo

### ISSUE THREAD

**Issue by NeedsMoar** [taabata/LCM_Inpaint_Outpaint_Comfy#5]
```
Traceback (most recent call last):
  File "C:\Programs\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Programs\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "C:\Programs\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM_Nodes.py", line 27, in <module>
    from .rival.ddim_inversion import Inversion, load_512
ModuleNotFoundError: No module named 'LCM_Inpaint-Outpaint_Comfy.rival'
```

I'm going to pull the current version of RIVAL from their repo at https://github.com/dvlab-research/RIVAL/, install the requirements, and copy the rival directory into the node directory to see if that makes it work.

**Comment by taabata** [comment]
just updated the code....these nodes were not supposed to be in the script

**Comment by NeedsMoar** [comment]
Ah ok.  Was just gonna post that adding the rival code didn't work because the nodes appeared to be looking for custom LCM functionality that isn't in RIVAL's main repo.  Probably better that it's just not supposed to be there then.  :D   I'll close this after I update and double check.
